In [17]:
#3 python to numPy array
import numpy as np
list1 = [1, 2, 3, 4, 5]
a = np.array(list1)
print("NumPy array:")
print(a)


NumPy array:
[1 2 3 4 5]


In [16]:
#2 1D array
import numpy as np
a = np.linspace(5, 50, 10)
print("10 evenly spaced values:")
print(a)

10 evenly spaced values:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [15]:
#8 Arithmatic
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Arithmetic operations:")
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Arithmetic operations:
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [18]:
#4 Reverse 1D
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print("Reversed array:")
print(a[::-1])

Reversed array:
[5 4 3 2 1]


In [19]:
#10 Mean medium std derivation
import numpy as np
a = np.array([10, 20, 30, 40, 50])
print("Mean, Median and Standard Deviation:")
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Standard deviation:", np.std(a))

Mean, Median and Standard Deviation:
Mean: 30.0
Median: 30.0
Standard deviation: 14.142135623730951
